import { Recipe } from './types';

export const STATIC_RECIPES: Recipe[] = [
  // Breakfast
  {
    id: '1',
    recipeName: 'Classic Pancakes',
    ingredients: ['1 1/2 cups all-purpose flour', '3 1/2 tsp baking powder', '1 tsp salt', '1 tbsp white sugar', '1 1/4 cups milk', '1 egg', '3 tbsp melted butter'],
    instructions: ['In a large bowl, sift together the flour, baking powder, salt and sugar.', 'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.', 'Heat a lightly oiled griddle or frying pan over medium high heat.', 'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake.', 'Brown on both sides and serve hot.'],
    reasoning: 'A classic breakfast staple that is easy to make and customize.',
    category: 'Breakfast',
    imageHint: 'pancakes breakfast',
    isFavorited: false,
  },
  {
    id: '2',
    recipeName: 'Avocado Toast with Egg',
    ingredients: ['1 slice of whole-wheat bread', '1/2 avocado', '1 egg', 'Salt and pepper to taste', 'Red pepper flakes (optional)'],
    instructions: ['Toast the bread to your liking.', 'Mash the avocado and spread it on the toast.', 'Cook the egg as you like (fried, poached, or scrambled).', 'Place the egg on top of the avocado toast.', 'Season with salt, pepper, and red pepper flakes if desired.'],
    reasoning: 'A quick, nutritious, and protein-packed breakfast to start your day.',
    category: 'Breakfast',
    imageHint: 'healthy breakfast',
    isFavorited: false,
  },
  {
    id: '3',
    recipeName: 'Berry Smoothie Bowl',
    ingredients: ['1 cup frozen mixed berries', '1/2 banana', '1/2 cup Greek yogurt', '1/4 cup almond milk', 'Toppings: granola, fresh berries, chia seeds'],
    instructions: ['In a blender, combine frozen berries, banana, Greek yogurt, and almond milk.', 'Blend until smooth and thick.', 'Pour the smoothie into a bowl.', 'Top with granola, fresh berries, and a sprinkle of chia seeds.'],
    reasoning: 'A refreshing and antioxidant-rich breakfast that feels like a treat.',
    category: 'Breakfast',
    imageHint: 'green smoothie',
    isFavorited: false,
  },
  // Lunch
  {
    id: '4',
    recipeName: 'Quinoa Salad with Chickpeas',
    ingredients: ['1 cup cooked quinoa', '1 can (15 oz) chickpeas, rinsed', '1 cucumber, diced', '1 cup cherry tomatoes, halved', '1/4 red onion, finely chopped', 'Dressing: 3 tbsp olive oil, 1 lemon (juiced), salt, pepper'],
    instructions: ['In a large bowl, combine the cooked quinoa, chickpeas, cucumber, cherry tomatoes, and red onion.', 'In a small bowl, whisk together the olive oil, lemon juice, salt, and pepper.', 'Pour the dressing over the salad and toss to combine.', 'Serve chilled or at room temperature.'],
    reasoning: 'A light, refreshing, and protein-packed salad that is perfect for a healthy lunch.',
    category: 'Lunch',
    imageHint: 'salad',
    isFavorited: true,
  },
  {
    id: '5',
    recipeName: 'Caprese Sandwich',
    ingredients: ['2 slices of ciabatta bread', '1 tbsp pesto', '1 large tomato, sliced', '4 oz fresh mozzarella, sliced', 'Fresh basil leaves', 'Balsamic glaze'],
    instructions: ['Spread pesto on both slices of bread.', 'Layer one slice with tomato, mozzarella, and fresh basil.', 'Drizzle with balsamic glaze.', 'Top with the other slice of bread and serve immediately.'],
    reasoning: 'A simple yet elegant sandwich with fresh Italian flavors.',
    category: 'Lunch',
    imageHint: 'turkey sandwich',
    isFavorited: false,
  },
  {
    id: '6',
    recipeName: 'Spicy Lentil Soup',
    ingredients: ['1 tbsp olive oil', '1 onion, chopped', '2 carrots, chopped', '2 celery stalks, chopped', '2 cloves garlic, minced', '1 tsp cumin', '1/2 tsp paprika', '1/4 tsp cayenne pepper', '1 cup red lentils, rinsed', '4 cups vegetable broth', 'Salt and pepper to taste'],
    instructions: ['In a large pot, heat olive oil over medium heat. Add onion, carrots, and celery and cook until softened.', 'Stir in garlic, cumin, paprika, and cayenne pepper, and cook for another minute.', 'Add the rinsed lentils and vegetable broth. Bring to a boil, then reduce heat and simmer for 20-25 minutes, or until lentils are tender.', 'Season with salt and pepper to taste.'],
    reasoning: 'A hearty, warming, and flavorful soup that is packed with fiber and plant-based protein.',
    category: 'Lunch',
    imageHint: 'soup',
    isFavorited: false,
  },
  // Dinner
  {
    id: '7',
    recipeName: 'Lemon Herb Baked Salmon',
    ingredients: ['1 lb salmon fillet', '2 tbsp olive oil', '2 cloves garlic, minced', '1 tsp dried herbs (e.g., oregano, thyme)', '1 lemon, sliced', 'Salt and pepper to taste'],
    instructions: ['Preheat oven to 400°F (200°C).', 'Place the salmon on a baking sheet lined with parchment paper.', 'In a small bowl, mix together the olive oil, minced garlic, and dried herbs.', 'Brush the mixture over the salmon fillet.', 'Season with salt and pepper, and top with lemon slices.', 'Bake for 12-15 minutes, or until the salmon is cooked through.'],
    reasoning: 'An elegant and healthy dinner that is quick to prepare and rich in omega-3 fatty acids.',
    category: 'Dinner',
    imageHint: 'salmon fish',
    isFavorited: true,
  },
  {
    id: '8',
    recipeName: 'Mushroom Risotto',
    ingredients: ['1 tbsp olive oil', '1 lb mushrooms, sliced', '1 shallot, finely chopped', '1 1/2 cups Arborio rice', '1/2 cup dry white wine', '4-5 cups hot vegetable broth', '1/2 cup grated Parmesan cheese', '2 tbsp butter', 'Salt and pepper to taste'],
    instructions: ['In a large pan, heat olive oil and cook the mushrooms until browned. Remove and set aside.', 'In the same pan, add the shallot and cook until soft. Add the rice and toast for a minute.', 'Pour in the wine and cook until it has evaporated.', 'Add the hot broth one ladle at a time, stirring continuously and waiting for the liquid to be absorbed before adding more.', 'Once the rice is creamy and al dente, stir in the cooked mushrooms, Parmesan cheese, and butter.', 'Season with salt and pepper and serve immediately.'],
    reasoning: 'A creamy and comforting Italian classic that makes for a sophisticated vegetarian meal.',
    category: 'Dinner',
    imageHint: 'pasta',
    isFavorited: false,
  },
  {
    id: '9',
    recipeName: 'Chicken Stir-Fry',
    ingredients: ['1 lb chicken breast, cut into strips', '1 tbsp soy sauce', '1 tbsp cornstarch', '2 tbsp vegetable oil', '1 head of broccoli, cut into florets', '1 red bell pepper, sliced', '1 carrot, julienned', 'Sauce: 1/4 cup soy sauce, 2 tbsp honey, 1 tbsp rice vinegar, 1 tsp sesame oil, 1 clove garlic, minced'],
    instructions: ['In a bowl, toss the chicken with 1 tbsp soy sauce and cornstarch.', 'In a large skillet or wok, heat vegetable oil over high heat. Add the chicken and cook until browned. Remove from skillet.', 'Add the broccoli, bell pepper, and carrot to the skillet and stir-fry for 3-5 minutes.', 'Whisk together all sauce ingredients. Return the chicken to the skillet and pour the sauce over. Cook until the sauce thickens.', 'Serve over rice or noodles.'],
    reasoning: 'A quick, versatile, and delicious way to get your protein and vegetables in one dish.',
    category: 'Dinner',
    imageHint: 'vegetable stir-fry',
    isFavorited: false,
  },
  // Snacks
  {
    id: '10',
    recipeName: 'Roasted Chickpeas',
    ingredients: ['1 can (15 oz) chickpeas, rinsed and dried', '1 tbsp olive oil', '1/2 tsp paprika', '1/2 tsp garlic powder', 'Salt to taste'],
    instructions: ['Preheat oven to 400°F (200°C).', 'Toss the dried chickpeas with olive oil and seasonings.', 'Spread on a baking sheet in a single layer.', 'Roast for 20-30 minutes, until crispy.', 'Let cool slightly before eating.'],
    reasoning: 'A crunchy, savory, and healthy snack that is high in protein and fiber.',
    category: 'Snack',
    imageHint: 'salad',
    isFavorited: false,
  },
  {
    id: '11',
    recipeName: 'Energy Bites',
    ingredients: ['1 cup rolled oats', '1/2 cup peanut butter', '1/3 cup honey or maple syrup', '1/2 cup ground flaxseed', '1/2 cup chocolate chips', '1 tsp vanilla extract'],
    instructions: ['In a bowl, combine all ingredients and mix well.', 'Chill the mixture in the refrigerator for about 30 minutes.', 'Roll into small, bite-sized balls.', 'Store in an airtight container in the fridge.'],
    reasoning: 'A no-bake, easy-to-make snack that provides a quick boost of energy.',
    category: 'Snack',
    imageHint: 'cookies',
    isFavorited: false,
  },
  // Desserts
  {
    id: '12',
    recipeName: 'Chocolate Avocado Mousse',
    ingredients: ['2 ripe avocados', '1/2 cup unsweetened cocoa powder', '1/2 cup maple syrup', '1/4 cup almond milk', '1 tsp vanilla extract', 'Pinch of salt'],
    instructions: ['Combine all ingredients in a blender or food processor.', 'Blend until completely smooth.', 'Divide the mousse into serving dishes and chill for at least 30 minutes before serving.'],
    reasoning: 'A surprisingly healthy and decadent dessert that is rich, creamy, and dairy-free.',
    category: 'Dessert',
    imageHint: 'chocolate brownie',
    isFavorited: false,
  },
  {
    id: '13',
    recipeName: 'Apple Crumble',
    ingredients: ['4 apples, peeled and sliced', '1/4 cup sugar', '1 tsp cinnamon', 'Topping: 1 cup rolled oats, 1/2 cup flour, 1/2 cup brown sugar, 1/2 cup cold butter, cubed'],
    instructions: ['Preheat oven to 375°F (190°C).', 'In a bowl, toss the apples with sugar and cinnamon. Spread in a baking dish.', 'For the topping, combine oats, flour, and brown sugar. Cut in the cold butter until the mixture resembles coarse crumbs.', 'Sprinkle the topping over the apples.', 'Bake for 30-40 minutes, or until the topping is golden and the apples are tender.'],
    reasoning: 'A warm and comforting dessert that is perfect for any occasion.',
    category: 'Dessert',
    imageHint: 'cake',
    isFavorited: false,
  },
];
